-- This SQL script contains the appropriate DML that must be run on the 
-- "dars_dwh_etl_db" database *after* the default metatdata is generated by the 
-- PDI job:
--
--     /psa/jb_psa-populate_metadata_tables.kjb .
--
-- This file contains adjustment SQL commands only for tables associated with
-- the "obo" tables in the PSA DB. If there are tables in the PSA DB that are
-- associated with other databases, the adjustment commands will be found in
-- other files in the same directory where this file is stored. All such 
-- adjustment scripts must be executed if the PDI job generates default metadata
-- for tables that original in all of these databases.
--
-- This SQL should be executed in a transaction in case syntax errors or any
-- other types of errors are introduced.


--------------------------------------------------------------------------------
-- Create rows for the metadata tables that cannot be created automagically by 
-- the PDI job:
--
--     /psa/jb_psa-populate_metadata_tables.kjb
--
-- These rows will generally be associated with tables that are maintained by
-- *custom* ETL code.
--
--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
-- Specify target column names that are not the same as the source column name:
--
-- If incorrect details are specified here, they will probably be caught when 
-- the ETL code runs because errors will be triggered if the column names are
-- wrong.
--
--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
-- Specify columns of source tables to *not* compare:
--
-- This is a "bytea" column, which can probably hold a lot of data. I 
-- experienced an "out of memory" crash once when comparing this source 
-- "obo_opr" table with its target PSA table. Another time, I did not trigger
-- that error and the compare reported no problems. Therefore, I have decided
-- to exclude this column from future "compare" jobs since I believe the ETL
-- update job is treating this column correctly. By comparing the remaining 
-- columns, I will at least catch other CDC-related problems.
UPDATE etl.column_meta cm SET compare_column=false FROM etl.table_meta tm 
WHERE
    tm.table_meta_id=cm.table_meta_id AND
    tm.source_db_id=2 AND tm.target_db_id=10 AND tm.source_table_name='engineering_data' AND cm.source_column_name='data_payload';
--------------------------------------------------------------------------------

