#!/bin/sh
set -e

# NOTE: We must be aligned with properties <app.rootDir>, <app.user> & <app.group> in pom.xml:
APP_ROOTDIR=/opt/qfree
APP_USER=etl
APP_GROUP=etl

# Where the ETL definition will be installed:
APP_DIR=${APP_ROOTDIR}/${APP_USER}

# Where the configuration files will be deployed:
CONF_DIR=${APP_DIR}/conf

# Install log filename:
INST_LOG=${APP_DIR}/logs/dwh-etl_install.log

case "$1" in

	configure)

		# Set the appropriate environment variables for the $APP_USER user
		DATE=`date +%Y-%m-%d:%H:%M:%S`
		if [ ! -e /home/$APP_USER/.profile ]; then
			cp  ${APP_DIR}/templates/dwh-etl.env /home/$APP_USER/.profile
			chown $APP_USER:$APP_GROUP /home/$APP_USER/.profile
			echo "$DATE - INFO: Created /home/$APP_USER/.profile for user $APP_USER." >> $INST_LOG
		else
			echo "$DATE - SKIPPED: creation of: /home/$APP_USER/.profile for user $APP_USER, ALREADY EXISTS" >> $INST_LOG
		fi

		# Install customer-specific configuration properties file:
		DATE=`date +%Y-%m-%d:%H:%M:%S`
		if [ ! -e ${CONF_DIR}/dwh.properties ]; then
			cp ${APP_DIR}/templates/dwh.properties ${CONF_DIR}/dwh.properties
			chown $APP_USER:$APP_GROUP ${CONF_DIR}/dwh.properties
			chmod 666 ${CONF_DIR}/dwh.properties
			echo "$DATE - INFO: Created DWH config: ${CONF_DIR}/dwh.properties." >> $INST_LOG
		else
			echo "$DATE - SKIPPED: creation of DWH config: ${CONF_DIR}/dwh.properties, ALREADY EXISTS" >> $INST_LOG
		fi

		# Install Q-Free-specific configuration properties file:
		DATE=`date +%Y-%m-%d:%H:%M:%S`
		if [ ! -e ${CONF_DIR}/dwh-qfree.properties ]; then
			cp  ${APP_DIR}/templates/dwh-qfree.properties ${CONF_DIR}/dwh-qfree.properties
			chown $APP_USER:$APP_GROUP ${CONF_DIR}/dwh-qfree.properties
			chmod 640 ${CONF_DIR}/dwh-qfree.properties
			echo "$DATE - INFO: Created Q-Free DWH specific props: ${CONF_DIR}/dwh-qfree.properties" >> $INST_LOG
		else
			echo "$DATE - SKIPPED: creation of Q-Free DWH specific props: ${CONF_DIR}/dwh-qfree.properties, ALREADY EXISTS" >> $INST_LOG
		fi

		# Install cron-job for user $APP_USER. The name of the file is set to
		# [[artifactId]], which should be relatively unique.
		DATE=`date +%Y-%m-%d:%H:%M:%S`
		if [ ! -e /etc/cron.d/[[artifactId]] ]; then
			cp  ${APP_DIR}/templates/dwh-etl.cron /etc/cron.d/[[artifactId]]
			echo "$DATE - INFO: Created [[artifactId]] execution cron job: /etc/cron.d/[[artifactId]]" >> $INST_LOG
		else
			echo "$DATE - SKIPPED: creation of [[artifactId]] execution cron job: /etc/cron.d/[[artifactId]], ALREADY EXISTS" >> $INST_LOG
		fi

		;;

	abort-upgrade|abort-deconfigure|abort-remove)
		;;

	*)
		echo "$0 called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

#DEBHELPER#
exit 0
