#!/bin/sh

set -e

# NOTE: We must be aligned with properties <app.rootDir>, <app.user> & <app.group> in pom.xml:
APP_ROOTDIR=/opt/qfree
APP_USER=etl
APP_GROUP=etl

case "$1" in
    install|upgrade)

#        # Create "tdp" user if it doesn't exist.
#        if ! id tdp > /dev/null 2>&1 ; then
#            adduser --system --home /home/tdp --group --shell /bin/bash tdp
#        fi

        # Create "${APP_USER}" user if it doesn't exist.
        if ! id ${APP_USER} > /dev/null 2>&1 ; then
            adduser --system --home /home/${APP_USER} --group --shell /bin/bash ${APP_USER}
        fi
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0