-- This SQL script contains the appropriate DML that must be run on the 
-- "etl_mgmt" database *after* the default metatdata is generated by the 
-- PDI job:
--
--     /dsa/jb_dsa-repopulate_metadata_tables.kjb .
--
-- This file contains adjustment SQL commands only for tables associated with
-- the "mon" tables in the PSA DB. If there are tables in the PSA DB that are
-- associated with other databases, the adjustment commands will be found in
-- other files in the same directory where this file is stored. All such 
-- adjustment scripts must be executed if the PDI job generates default metadata
-- for tables that original in all of these databases.
--
-- This SQL should be executed in a transaction in case syntax errors or any
-- other types of errors are introduced.


--------------------------------------------------------------------------------
-- Create rows for the metadata tables that cannot be created automagically by 
-- the PDI job:
--
--     /dsa/jb_dsa-repopulate_metadata_tables.kjb
--
-- These rows will generally be associated with tables that are maintained by
-- *custom* ETL code.
--
-- Target table: 
--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
-- Specify target column names that are not the same as the source column name:
--
-- If incorrect details are specified here, they will probably be caught when 
-- the ETL code runs because errors will be triggered if the column names are
-- wrong.
--
-- Source table: 
--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
-- Specify columns of source tables to *not* mirror and *not* compare:
UPDATE etl.column_meta cm SET mirror_column=false, compare_column=false FROM etl.table_meta tm 
WHERE 
    cm.table_meta_id=tm.table_meta_id AND 
    tm.source_db_id=10 AND tm.source_schema_name='public' AND tm.target_db_id=20 AND tm.target_schema_name='public' AND  -- PSA -> DSA
    
    -- These conditions list all of the columns of each source table that *shall* be mirrored and compared.
    -- The "NOT IN" operator is then used to update all of the *remaining* column_meta rows to specify 
    -- that they will *not* be mirrored or compared. The "source" column names are used here, in case
    -- the target column names change. This should reduce the number of changes necessary if the target 
    -- column names change and, therefore, make this code less brittle when such changes are introduced:
    (
        tm.source_table_name='mon__data_collection_source' AND cm.source_column_name NOT IN (
            'dcs_id', 
            'source_hostname', 
            'source_component_name',
            'created_on',
            'last_updated_on')
     OR tm.source_table_name='mon__managed_objects' AND cm.source_column_name NOT IN (
            'managed_object_id', 
            'managed_object_name', 
            'created_on',
            'last_updated_on')
     OR tm.source_table_name='mon__alarms' AND cm.source_column_name NOT IN (
            'alarm_id', 
            'managed_object_id', 
            'last_event_description')
     OR tm.source_table_name='mon__alarm_actions' AND cm.source_column_name NOT IN (
            'alarm_action_id', 
            'alarm_id', 
            'alarm_action_type_id', 
            'action_timestamp')
     OR tm.source_table_name='mon__alarm_action_type' AND cm.source_column_name NOT IN (
            'alarm_action_type_id', 
            'enum_name', 
            'description')
--     OR tm.source_table_name='mon__' AND cm.source_column_name NOT IN (
--            '', 
--            '', 
--            '', 
--            '', 
--            '')
    );
--------------------------------------------------------------------------------
